{"stats": {"errors": 0, "failures": 1, "passes": 0, "skipped": 0, "encoding": "UTF-8", "total": 1}, "results": [{"classname": "index_test:FieldElementTest", "name": "test_div", "time": 0.00044536590576171875, "type": "failure", "errtype": "builtins.AssertionError", "message": "FieldElement_31(28) != FieldElement_31(29)", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/pb-tester-ccdle12/ecc-div-jsong-pb-sf-072618/test/index_test.py\", line 11, in test_div\n    self.assertEqual(a**-3, FieldElement(29, 31))\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 822, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: FieldElement_31(28) != FieldElement_31(29)\n"}]}